# Image for experimenting with Minlog

FROM debian
MAINTAINER Trifon Trifonov <triffon@fmi.uni-sofia.bg>

RUN apt-get update && apt-get install -y locales make chezscheme emacs-nox git
RUN git clone https://github.com/triffon/minlog.git /usr/src/minlog
WORKDIR /usr/src/minlog
RUN make
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
CMD /usr/src/minlog/minlog
